# Generated by Django 3.0.3 on 2020-02-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdetails',
            name='email1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='email10',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='email11',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='email12',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='email2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='email3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='email4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='email5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='email6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='email7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='email8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='email9',
            field=models.TextField(),
        ),
    ]
