# Generated by Django 3.0.3 on 2020-02-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20200213_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdetails',
            name='phone1',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='phone10',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='phone11',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='phone12',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='phone2',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='phone3',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='phone4',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='phone5',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='phone6',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='phone7',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='phone8',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdetails',
            name='phone9',
            field=models.TextField(default=0),
        ),
    ]
